# language: node_js
# node_js: lts/*
# sudo: false
# before_cache:
#     rm -rf node_modules/.cache
# cache:
#   yarn: true
#   directories:
#     - node_modules
# before_install:
# - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
# - export PATH=$HOME/.yarn/bin:$PATH
# install:
# - yarn install
# script:
# - yarn test
# - yarn build
# deploy:
#   provider: surge
#   skip_cleanup: true
#   domain: tientran0019-reactjs.surge.sh
#   project: ./build/
# on:
#   branch: master
